// <auto-generated />
namespace PhoneComp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addcreatedate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcreatedate));
        
        string IMigrationMetadata.Id
        {
            get { return "201404030336529_addcreatedate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
