// <auto-generated />
namespace PhoneComp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class callrecordreq : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(callrecordreq));
        
        string IMigrationMetadata.Id
        {
            get { return "201404010555513_callrecordreq"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
