// <auto-generated />
namespace PhoneComp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Addmember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addmember));
        
        string IMigrationMetadata.Id
        {
            get { return "201404250859184_Addmember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
