// <auto-generated />
namespace PhoneComp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class lastupdateuserid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastupdateuserid));
        
        string IMigrationMetadata.Id
        {
            get { return "201404260307043_lastupdateuserid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
